[package]
edition = "2021"
name = "playground"
version = "0.1.0"

[[bin]]
name = "playground"
path = "bin.rs"

[dependencies]
image = "0.24"
ndarray = "0.15.6"
num-complex = "0.4"
palette = "0.7"
plotters = "0.3"
rustfft = "6"
